[2025-08-07T00:09:11.990+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-07T00:09:12.003+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_snowflake_loader.load_holiday_events_to_snowflake manual__2025-08-07T00:09:07.574394+00:00 [queued]>
[2025-08-07T00:09:12.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_snowflake_loader.load_holiday_events_to_snowflake manual__2025-08-07T00:09:07.574394+00:00 [queued]>
[2025-08-07T00:09:12.008+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-07T00:09:12.023+0000] {taskinstance.py:2330} INFO - Executing <Task(SnowflakeOperator): load_holiday_events_to_snowflake> on 2025-08-07 00:09:07.574394+00:00
[2025-08-07T00:09:12.038+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8019) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-07T00:09:12.042+0000] {standard_task_runner.py:63} INFO - Started process 8032 to run task
[2025-08-07T00:09:12.041+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_to_snowflake_loader', 'load_holiday_events_to_snowflake', 'manual__2025-08-07T00:09:07.574394+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/load/s3_to_snowflake_loader.py', '--cfg-path', '/tmp/tmp3t099nyj']
[2025-08-07T00:09:12.051+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask load_holiday_events_to_snowflake
[2025-08-07T00:09:12.114+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-07T00:09:12.200+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_to_snowflake_loader.load_holiday_events_to_snowflake manual__2025-08-07T00:09:07.574394+00:00 [running]> on host 3bffe12d583b
[2025-08-07T00:09:12.300+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_snowflake_loader' AIRFLOW_CTX_TASK_ID='load_holiday_events_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-08-07T00:09:07.574394+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-07T00:09:07.574394+00:00'
[2025-08-07T00:09:12.301+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-07T00:09:12.309+0000] {sql.py:276} INFO - Executing: 
            COPY INTO RAW_HOLIDAY_EVENTS
            FROM 's3://favorita-retail-pipeline/raw/holiday_events.csv'
            CREDENTIALS = (
                AWS_KEY_ID= 'ASIAVX5O2PQE76MTG36M',
                AWS_SECRET_KEY= '***',
                AWS_TOKEN= '***'
            )
            FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);
            
[2025-08-07T00:09:12.322+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2025-08-07T00:09:12.331+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2025-08-07T00:09:12.332+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-08-07T00:09:12.333+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-08-07T00:09:13.023+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-08-07T00:09:13.024+0000] {sql.py:470} INFO - Running statement: COPY INTO RAW_HOLIDAY_EVENTS
            FROM 's3://favorita-retail-pipeline/raw/holiday_events.csv'
            CREDENTIALS = (
                AWS_KEY_ID= 'ASIAVX5O2PQE76MTG36M',
                AWS_SECRET_KEY= '***',
                AWS_TOKEN= '***'
            )
            FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);, parameters: None
[2025-08-07T00:09:13.198+0000] {connection.py:762} INFO - closed
[2025-08-07T00:09:13.253+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2025-08-07T00:09:13.318+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-07T00:09:13.322+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 395, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 091003 (22000): 01be32e9-0000-29a7-0000-003d698bc091: Failure using stage area. Cause: [User: arn:aws:sts::394966760457:assumed-role/voclabs/user4052228=MBADRILA@depaul.edu is not authorized to perform: s3:ListBucket on resource: "arn:aws:s3:::favorita-retail-pipeline" with an explicit deny in an identity-based policy (Status Code: 403; Error Code: AccessDenied)]
[2025-08-07T00:09:13.340+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=s3_to_snowflake_loader, task_id=load_holiday_events_to_snowflake, run_id=manual__2025-08-07T00:09:07.574394+00:00, execution_date=20250807T000907, start_date=20250807T000912, end_date=20250807T000913
[2025-08-07T00:09:13.360+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 76 for task load_holiday_events_to_snowflake (091003 (22000): 01be32e9-0000-29a7-0000-003d698bc091: Failure using stage area. Cause: [User: arn:aws:sts::394966760457:assumed-role/voclabs/user4052228=MBADRILA@depaul.edu is not authorized to perform: s3:ListBucket on resource: "arn:aws:s3:::favorita-retail-pipeline" with an explicit deny in an identity-based policy (Status Code: 403; Error Code: AccessDenied)]; 8032)
[2025-08-07T00:09:13.388+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-07T00:09:13.403+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
