[2025-08-06T23:48:52.121+0000] {processor.py:161} INFO - Started process (PID=7375) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:48:52.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:48:52.126+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:48:52.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:48:52.135+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:48:52.132+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= aws_creds.access_key,
                ^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:48:52.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:48:52.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.047 seconds
[2025-08-06T23:49:22.669+0000] {processor.py:161} INFO - Started process (PID=7390) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:49:22.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:49:22.676+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:49:22.675+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:49:22.681+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:49:22.680+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= aws_creds.access_key,
                ^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:49:22.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:49:22.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.053 seconds
[2025-08-06T23:49:53.168+0000] {processor.py:161} INFO - Started process (PID=7405) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:49:53.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:49:53.175+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:49:53.174+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:49:53.181+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:49:53.180+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= aws_creds.access_key,
                ^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:49:53.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:49:53.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.054 seconds
[2025-08-06T23:50:23.667+0000] {processor.py:161} INFO - Started process (PID=7420) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:50:23.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:50:23.673+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:50:23.672+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:50:23.677+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:50:23.676+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= aws_creds.access_key,
                ^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:50:23.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:50:23.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.046 seconds
[2025-08-06T23:50:54.171+0000] {processor.py:161} INFO - Started process (PID=7435) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:50:54.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:50:54.179+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:50:54.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:50:54.186+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:50:54.183+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= aws_creds.access_key,
                ^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:50:54.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:50:54.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.045 seconds
[2025-08-06T23:51:24.582+0000] {processor.py:161} INFO - Started process (PID=7450) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:51:24.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:51:24.590+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:51:24.590+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:51:24.595+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:51:24.594+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= aws_creds.access_key,
                ^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:51:24.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:51:24.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.049 seconds
[2025-08-06T23:51:55.152+0000] {processor.py:161} INFO - Started process (PID=7465) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:51:55.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:51:55.161+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:51:55.161+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:51:55.166+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:51:55.165+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= aws_creds.access_key,
                ^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:51:55.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:51:55.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.050 seconds
[2025-08-06T23:52:25.689+0000] {processor.py:161} INFO - Started process (PID=7480) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:52:25.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:52:25.694+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:52:25.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:52:25.701+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:52:25.699+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= aws_creds.access_key,
                ^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:52:25.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:52:25.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.051 seconds
[2025-08-06T23:52:41.990+0000] {processor.py:161} INFO - Started process (PID=7495) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:52:41.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:52:41.995+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:52:41.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:52:42.000+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:52:41.999+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:52:42.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:52:42.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.053 seconds
[2025-08-06T23:53:12.487+0000] {processor.py:161} INFO - Started process (PID=7510) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:12.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:53:12.496+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:12.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:12.501+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:12.500+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:53:12.501+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:12.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.060 seconds
[2025-08-06T23:53:24.641+0000] {processor.py:161} INFO - Started process (PID=7515) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:24.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:53:24.647+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:24.647+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:24.655+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:24.651+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:53:24.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:24.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.054 seconds
[2025-08-06T23:53:25.644+0000] {processor.py:161} INFO - Started process (PID=7520) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:25.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:53:25.647+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:25.647+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:25.650+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:25.649+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:53:25.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:25.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.024 seconds
[2025-08-06T23:53:26.670+0000] {processor.py:161} INFO - Started process (PID=7525) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:26.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:53:26.673+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:26.672+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:26.675+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:26.675+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:53:26.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:26.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.021 seconds
[2025-08-06T23:53:27.715+0000] {processor.py:161} INFO - Started process (PID=7530) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:27.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:53:27.717+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:27.717+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:27.721+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:27.720+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:53:27.721+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:27.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.025 seconds
[2025-08-06T23:53:58.305+0000] {processor.py:161} INFO - Started process (PID=7545) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:58.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:53:58.313+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:58.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:58.318+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:53:58.317+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:53:58.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:53:58.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.050 seconds
[2025-08-06T23:54:28.935+0000] {processor.py:161} INFO - Started process (PID=7560) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:54:28.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:54:28.941+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:54:28.940+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:54:28.946+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:54:28.945+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:54:28.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:54:28.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.047 seconds
[2025-08-06T23:54:59.391+0000] {processor.py:161} INFO - Started process (PID=7575) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:54:59.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:54:59.397+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:54:59.397+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:54:59.403+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:54:59.401+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:54:59.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:54:59.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.045 seconds
[2025-08-06T23:55:29.781+0000] {processor.py:161} INFO - Started process (PID=7590) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:55:29.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:55:29.790+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:55:29.789+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:55:29.795+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:55:29.794+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:55:29.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:55:29.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.051 seconds
[2025-08-06T23:56:00.266+0000] {processor.py:161} INFO - Started process (PID=7605) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:56:00.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:56:00.272+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:56:00.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:56:00.277+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:56:00.275+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:56:00.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:56:00.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.046 seconds
[2025-08-06T23:56:30.774+0000] {processor.py:161} INFO - Started process (PID=7620) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:56:30.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:56:30.780+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:56:30.780+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:56:30.791+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:56:30.790+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:56:30.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:56:30.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.051 seconds
[2025-08-06T23:56:55.284+0000] {processor.py:161} INFO - Started process (PID=7635) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:56:55.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:56:55.288+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:56:55.287+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:56:55.292+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:56:55.291+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:56:55.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:56:55.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.035 seconds
[2025-08-06T23:57:25.726+0000] {processor.py:161} INFO - Started process (PID=7650) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:57:25.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:57:25.734+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:57:25.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:57:25.744+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:57:25.742+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:57:25.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:57:25.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.055 seconds
[2025-08-06T23:57:56.072+0000] {processor.py:161} INFO - Started process (PID=7665) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:57:56.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:57:56.075+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:57:56.075+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:57:56.079+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:57:56.078+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:57:56.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:57:56.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.027 seconds
[2025-08-06T23:58:26.470+0000] {processor.py:161} INFO - Started process (PID=7680) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:58:26.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:58:26.477+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:58:26.476+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:58:26.482+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:58:26.481+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:58:26.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:58:26.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.038 seconds
[2025-08-06T23:58:29.516+0000] {processor.py:161} INFO - Started process (PID=7685) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:58:29.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:58:29.518+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:58:29.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:58:29.522+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:58:29.521+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:58:29.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:58:29.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.029 seconds
[2025-08-06T23:59:00.134+0000] {processor.py:161} INFO - Started process (PID=7700) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:59:00.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:59:00.143+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:59:00.140+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:59:00.149+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:59:00.148+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:59:00.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:59:00.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.062 seconds
[2025-08-06T23:59:30.830+0000] {processor.py:161} INFO - Started process (PID=7715) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:59:30.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-06T23:59:30.844+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:59:30.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:59:30.850+0000] {logging_mixin.py:188} INFO - [2025-08-06T23:59:30.849+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-06T23:59:30.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-06T23:59:30.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.082 seconds
